version: '3.7'

services:

  web:
    container_name: http-server
    build:
      context: docker/httpd
      dockerfile: Dockerfile
    environment:
      - APACHE_RUN_USER=${APACHE_RUN_USER}
    ports:
      - 8080:80
    working_dir: /var/www/html/
    volumes:
      - "./:/var/www/html"

  db:
    container_name: dblar
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    ports:
      - 127.0.0.1:${MYSQL_CONTAINER_PORT}:3306


  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
